### ISSUE TITLE
undefined functions

### ISSUE THREAD

**Issue by izahn** [tdhock/mclapply-memory#1]
I'd like to reproduce this, but both `works_with_R` and `memtime` are undefined.

**Comment by tdhock** [comment]
I recommend copying the definition of works_with_R from https://github.com/tdhock/dotfiles/blob/master/.Rprofile to your .Rprofile

after that you should be able to type make on the command line to reproduce this (on a computer with GNU free)

memtime is from https://github.com/tdhock/memtime

**Comment by izahn** [comment]
That seems more complicated than it should be -- why not just put `devtools::install_github(tdhock/memtime)` at the top of the script? In any case I had to re-write `memtest` since `free` appears to format the output differently on my system. But I did get it working and found results very similar to yours.
