### ISSUE TITLE
Questions about memory usage

### ISSUE THREAD

**Issue by traversc** [tdhock/mclapply-memory#2]
Thanks for putting this report together, I also noticed extreme memory usage when using mclapply and couldn't find any discussion about it on the internet.  Do you know why it the memory blows up, when a corresponding lapply does not?  What else is occupying the memory, besides the return value, is it a bug?  

Thanks

**Comment by tdhock** [comment]
I don't know why it happens, but I was able to avoid memory problems using "maxjobs.mclapply" -- a function that simply calls mclapply several times, on smaller data subsets https://github.com/tdhock/mclapply-memory/blob/master/kilobytes.used.R#L12 If you think this is an issue (as I did), you may want to report it to R-devel, but you may want to try to construct a more complicated/non-trivial example than I did https://github.com/tdhock/mclapply-memory#question-and-response-on-r-devel

**Comment by traversc** [comment]
I originally tried something like maxjobs.mclapply, but for my applications, even a few jobs blew up the memory.  Based on your analysis showing that a NULL return doesn't affect the memory much, I realized there was another possible solution: write the results of each iteration to a temporary file, and at the end of the loop, read the results from disk.  

    null.mclapply <- function(X,FUN,mc.cores,...) {
    require(parallel)
    base <- paste0(tempdir(),"/",paste0(sample(c(letters,LETTERS,0:9), replace=T,size=12),collapse=""))

    message(paste0("Saving results to ",base))
    mclapply(seq_along(X),function(i) {
        saveRDS(FUN(X[i]),file=paste0(base,"_",i,".Rds"),compress=F)
        return(NULL)
    }, mc.cores=mc.cores,...)
    message(paste0("Reading results from ",base))
    mclapply(seq_along(X),function(i) {
        readRDS(paste0(base,"_",i,".Rds"))
    },mc.cores=mc.cores,...)
    }

Anyway, thanks again.  I definitely think it's an important issue R developers should address.

**Comment by tdhock** [comment]
that is an interesting hack! thanks for the idea.
